// Embeds supabase/functions/app/index.html into app/html.ts so the UI ships inside the function bundle
// with no dependency on config.toml static_files (which needs Docker at deploy time). Run: deno task embed
const src = await Deno.readTextFile("supabase/functions/app/index.html");
await Deno.writeTextFile("supabase/functions/app/html.ts", "// GENERATED by scripts/embed.ts — do not edit. Source: index.html\nexport const HTML = " + JSON.stringify(src) + ";\n");
console.log(`embedded ${src.length} chars`);
